### ISSUE TITLE
Use Calver ?

### ISSUE THREAD

**Issue by Carreau** [Quansight-Labs/intersphinx_registry#4]
I'm thinking we could use CalVer, as this package may reflect changes in url through time, 
thus the time of package publication has more impact than it's actual version.

There are multiple proposition below please vote with 👍 👎

**Comment by Carreau** [comment]
There is also semi-calver: `major.YYYYMMDD.patch`.

**Comment by Carreau** [comment]
`YEAR.MM.DD`

**Comment by tacaswell** [comment]
Although, I'm skeptical of the likely hood of multiple release per-day (worst case we steal tomorrows date) so `major.YYMM.DD` would be my vote.
